name: build lib

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    name: "build lib"
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: create build user
        run: |
          pacman -Syu --needed --noconfirm sudo # Install sudo
          useradd builduser -m # Create the builduser
          passwd -d builduser # Delete the builduser's password
          printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers # Allow the builduser passwordless sudo
      - uses: actions/checkout@v4
      - name: Install Packages
        run: |
          pacman -Syu --noconfirm base-devel git nasm jq ninja cpio wget unzip cmake
          pacman -Syu --noconfirm qt6-wayland qt6-declarative
      - name: Install session-lock
        run: |
          cd asserts
          sudo -u builduser makepkg
          pacman -U *.pkg.tar.zst
          cd ..
      - name: Build
        run: |
          cmake -B build
          cmake --build build
